### ISSUE TITLE
Allow items to be moved off characters with no remaining items

### ISSUE THREAD

**Issue by chrisfried** [kyleshay/DIM#1]
Let's say you want to move your Ice Breaker from your Warlock to your Hunter. However, the Warlock has no other Secondary guns in its inventory. Currently, the transfer fails. The script should:

1. Recognize this
2. Check for an appropriate item to give the Warlock:
  1. In the Vault
  2. In uninvolved characters' inventories
  3. In the Hunter's inventory
3. If an item is found available, it should be given to the Warlock
4. If successful, Ice Breaker should be transferred to the Hunter. 
5. Possibly, the item previously equipped by the Hunter should then be transferred to the Warlock. I'm uncertain if that would be expected effect.
6. If so, the placeholder item should then returned to its original location

**Comment by Sunblood** [comment]
Unrelated to DIM, but for a while now I've had one basic white primary, secondary, and heavy on each character that are just there to allow me to remove all other weapons. Easily obtainable from the Cryptarch. White so they don't get mixed in with green/blue engrams. Works pretty well with DIM.

**Comment by SunburnedGoose** [comment]
Added to v3.
