### ISSUE TITLE
Constantly tells me to log into bungie.net

### ISSUE THREAD

**Issue by jmichas** [kyleshay/DIM#105]
The old version worked great, the latest version continually tells me to login to bungie although I am already. This is on chrome on OSX, I tried reinstalling the plugin, restarting chrome, and logging out and into bungie again, no change.

Any suggestions?

**Comment by SunburnedGoose** [comment]
What worked for me was going to Settings -> Show Advanced Settings -> Content Settings -> All cookies and site data -> Search for 'bungie', and click 'Remove all shown'.

**Comment by jmichas** [comment]
Cool. Thanks! That fixed it. I thought logging out and in would have reset the cookie, but I guess there are other cookies that don't get reset.

**Comment by snowilli** [comment]
Had the same problem and this resolved the issue. Thanks!
