### ISSUE TITLE
Cannot create more than 9 loadouts

### ISSUE THREAD

**Issue by matthewk85** [kyleshay/DIM#108]
I had 11 loadouts, when i logged back in there were only 9. I tried recreating the missing ones and after a refresh they had disappeared again.

**Comment by Subject22** [comment]
Have you tried logging out of Bungie.net, clearing your cookies, restarting Chrome etc.?

**Comment by matthewk85** [comment]
Have logged out and into Bungie.net, but haven't cleared cookies, will try when i next have the opportunity and report back.

**Comment by SunburnedGoose** [comment]
There is a maximum file size we can save and you're probably going over.

**Comment by SunburnedGoose** [comment]
Okay.  I can't compress the file.  I have to store them as JSON and the JSON files can't be over 100k.  We're gonna have to give up on storage sync if we're gonna support more than 5-10 loadouts (depending on the number of items).

**Comment by m-s-y** [comment]
What about using something like http://pieroxy.net/blog/pages/lz-string/index.html where Chrome's local JSON object storage looks like a single JSON pair:
```
StorageArea.set( object {"dim":"compressedBLOB"} )
``` 
where _compressedBLOB_ is the result of a compression function, something like:
```
compressedBLOB = compress( dimJsonObject )
```
Then to load it out, just reverse the process

**Comment by SunburnedGoose** [comment]
Didn't want to use local storage. I was trying to recall LZ string. Thanks
for finding it.
