### ISSUE TITLE
Determine chrome adoption rate. Are we safe to use a function only in chrome v42?

### ISSUE THREAD

**Issue by kyleshay** [kyleshay/DIM#117]
I just got an update for chrome -- v42-- should we push the change for opening the page?

doing so will remove the permission for 'requiring access to history' or whatever it claims... since chrome auto updates, is it possible that people may still be on v41?

https://developer.chrome.com/extensions/runtime#method-openOptionsPage

this would be huge. lots of people are really turned off to DIM because of that permission.

**Comment by SunburnedGoose** [comment]
Can you give me access to the google analytics?

**Comment by kyleshay** [comment]
done!

here is some info pulled
![img](http://i.imgur.com/JynCd82.png)

**Comment by SunburnedGoose** [comment]
~10% of the population. Does this cover the past two months? Didn't 42 come
out in this timeframe.

**Comment by SunburnedGoose** [comment]
Past two weeks, only 1% was been Chrome 41.  Go for it.  btw, what's the
secret sauce that removed the dependency on browser history?

**Comment by kyleshay** [comment]
before:
![before](http://i.imgur.com/ncWYuD2.png)

after:
![after](http://i.imgur.com/rqxlLds.png)

**Comment by kyleshay** [comment]
before we needed to query the open tabs to see if DIM was open (aka "access to your browsing history") so that a new instance isn't opened.

open options page will automatically handle that stuff under the hood.

**Comment by phatsk** [comment]
After 3.0.3 I think this can be closed?

**Comment by kyleshay** [comment]
correct!

**Comment by SunburnedGoose** [comment]
Incognito mode is broken.  We can remove the tabs permission and still keep the previous opening strategy.  I've restored it dev and master branch.  I'll make v3.0.4 to fix this when you've had a chance to comment @kyleshay.

**Comment by phatsk** [comment]
@SunburnedGoose damn Incognito Mode! We just ran into a similar fringe case at work where Incognito doesn't like you accessing `localStorage` (Safari though, I think). Bah.

**Comment by SunburnedGoose** [comment]
:/

**Comment by kyleshay** [comment]
hmm, what's the fix then if we're removing the tabs permission?

**Comment by SunburnedGoose** [comment]
Old code works without tabs. Only need tabs if you change the url, favicon,
which we don't.

**Comment by kyleshay** [comment]
the reason we had tabs was so that we could determine if DIM was already open -- if a user clicks the DIM icon button again it will set that instance to the active tab. Right now every time you click the icon, it opens a new instance of DIM.

**Comment by SunburnedGoose** [comment]
I pulled the tabs permission out and it still worked, even after re-installing.

**Comment by kyleshay** [comment]
right, but if you click the DIM icon (after DIM is already open) it will open a new instance of DIM.

**Comment by SunburnedGoose** [comment]
Are we talking about the checked in version?  Yeah, but the original code works and does the check.  We need to go back to that.

**Comment by kyleshay** [comment]
ahhh----- sorry about that. i misunderstood.

just looked at the documentation again-https://developer.chrome.com/extensions/tabs

    You can use most chrome.tabs methods and events without declaring any permissions in the extension's manifest file. However, if you require access to the url, title, or favIconUrl properties of tabs.Tab, you must declare the "tabs" permission in the manifest, as shown below:

**Comment by SunburnedGoose** [comment]
The code I checked in was just me 'testing' boundaries.  We should revert and push.

**Comment by SunburnedGoose** [comment]
Also, google analytics is in the code twice :/ 

Once in the main.js, and again in app.config.js.  We should remove the main.js one.  The app.config.js is pulling the JS file from Google so it will always be up to date.

**Comment by kyleshay** [comment]
yupyup, sounds good!
