### ISSUE TITLE
New engrams introduced in Destiny 1.2 don't display.

### ISSUE THREAD

**Issue by chrisfried** [kyleshay/DIM#126]

**Comment by chrisfried** [comment]
Bungie:
![screenshot 2015-05-15 15 41 05](https://cloud.githubusercontent.com/assets/422381/7661511/dc5f7522-fb18-11e4-80f9-f96b2fda65c5.png)
DIM:
![screenshot 2015-05-15 15 41 12](https://cloud.githubusercontent.com/assets/422381/7661512/dc5ff114-fb18-11e4-834c-102fe0a425ab.png)

**Comment by SunburnedGoose** [comment]
I hasn't updated item defs yet.  Waiting for it to finish.

**Comment by SunburnedGoose** [comment]
I've got 3.0.4 ready to go.
