### ISSUE TITLE
items filtering as xpincomplete when they are not  (Likely a bungie API bug)

### ISSUE THREAD

**Issue by maurilax** [kyleshay/DIM#128]
I have a couple items that still show in when the xpincomplete filter is set even though they are max xp. I am guessing this is a bungie bug because other sites that use the api report the xp incorrectly as well. Just wanted to make sure.
![destiny_20150516162150](https://cloud.githubusercontent.com/assets/2760180/7667866/ed110f26-fbe9-11e4-9687-38b96480a9ef.jpg)
![2015-05-16_16-38-30](https://cloud.githubusercontent.com/assets/2760180/7667868/004a7384-fbea-11e4-9602-58c7e6a6db18.png)
![2015-05-16_16-40-22](https://cloud.githubusercontent.com/assets/2760180/7667873/4b278cb6-fbea-11e4-87c7-9239dcba28a2.png)

**Comment by SunburnedGoose** [comment]
Thanks. We will wait until HoW drops to see how it acts.

**Comment by SunburnedGoose** [comment]
Related to #125
