### ISSUE TITLE
All dependencies seem to be missing!

### ISSUE THREAD

**Issue by joshhunt** [kyleshay/DIM#133]
~~I did a git clone and tried to get chrome to load the unpack extension, but it failed to load - all the dependencies are missing!~~

~~index.html makes references to `vendor/`, but that isnt present in the folder. There also isnt a `bower.json` or `package.json` that defines the dependencies for me to download.~~

Also `processBungieManifest.js` won't run because it relies on some node modules which haven't been installed

Can you please consider defining these dependencies with a package manager to make it easier for others to get the project up and running to make contributions? I would create and add them to a `packages.json`/~~`bower.json`~~, but I'm don't know what version you're using

**Edit:** Silly me - I was blind to the `bower.json` in the project root. Still, a package.json would be nice for the node modules required.

**Comment by brandonkboswell** [comment]
Hey Josh, @SunburnedGoose has said he's going to add the package.json. However it's not necessary to add to this project. The only time you need to run processBungieManifest.js is when updating the item list. Which is probably only necessary one every expansion.

**Comment by joshhunt** [comment]
Yeah, this issue more or less became moot once I found the `bower.json` in the root of the project
