### ISSUE TITLE
Improve Start Up Performance

### ISSUE THREAD

**Issue by SunburnedGoose** [kyleshay/DIM#137]
jQuery helped right at the end of v3 to get several features into it quickly.  

The move-popups would be outside the window on the right hand side.
Showing the About, Filter, and Support dialogs.
Fixing the page so it doesn't shift when dialogs are shown.

Removing jQuery improved startup by 1 second.

Upgrading Angular to v1.4.0-rc.2.

Angular and ngAnimate both are much faster on startup with their lastest versions.  We save over a second on startup.

I was able to get v3 from ~5 seconds down to ~3 seconds if not lower.  

There is more that can be done from the perspective of manipulating the ng-repeats, and the manipulation of the data.  That's for another day.

**Comment by Subject22** [comment]
What about adding a refresh feature which allows users to force the extension to update its data without requiring a full reboot? From what I can see the reason the long boot time is annoying in the first place is that people often need to restart it to get it to sync after making some change to their inventory in-game.

**Comment by SunburnedGoose** [comment]
I've started working on that feature.

**Comment by Subject22** [comment]
Awesome :)
