### ISSUE TITLE
Need a Develop Branch

### ISSUE THREAD

**Issue by SunburnedGoose** [kyleshay/DIM#14]
I've got some big changes and it would be nice to have a develop branch to merge these pull requests into, then move into master.

Likewise, can you tag the codebase for each release?

**Comment by kyleshay** [comment]
yes, and yes. really have been intending to do this.

**Comment by kyleshay** [comment]
dev created -- i'll start tagging released

thanks :+1:

**Comment by SunburnedGoose** [comment]
Thanks!
