### ISSUE TITLE
DIM v3.0.11 - Not finding bungled cookie in bungie.net domain

### ISSUE THREAD

**Issue by matthubb** [kyleshay/DIM#146]
I'm using Chrome dev Version 44.0.2403.9 dev-m and DIM from the Google Store.

The `GetBungieNetUser` is getting `WebAuthRequired` back. The request contains cookies okay. On closer inspection, I've noticed that the `X-CSRF` is missing from this request.

Haven't been able to find anything about this header being controlled specifically by Chrome.

My workstation somewhere else is on Chrome Dev 44.0.2398.0 and DIM works fine with it, the header is present in the request.

Not found anything yet in the change log [here](https://chromium.googlesource.com/chromium/src/+log/44.0.2398.0..44.0.2403.4?pretty=fuller&n=10000) yet.

**Comment by SunburnedGoose** [comment]
Can you share your screen with me on google hangout?  I can't repo in Canary.

**Comment by matthubb** [comment]
Hmmm... tried it with incognito and it works, must be an extension interfering or something.

**Comment by SunburnedGoose** [comment]
Well, don't do anything.  You're a use case that I haven't been able to replicate.  Can you work with me on this?  Other people report not being able to log in and I haven't been able to figure it out.

**Comment by SunburnedGoose** [comment]
Don't delete cookies or anything like that.  Can you leave it pristine?

**Comment by matthubb** [comment]
Sure, certainly will. At least it works in incognito :)

**Comment by matthubb** [comment]
This is still an issue for me on my home Chrome, but as it wasn't a problem in my incognito, I guess it was an extension interfering or something.

The problem turns out to be that my `bungled` cookie is under the domain `bungie.net` and not `www.bungie.net` so that the `getBnetCookies` function doesn't return it.

No idea how this cookie arrangement came to be, but I don't do any development on this Chrome.
