### ISSUE TITLE
weird problem with DIM

### ISSUE THREAD

**Issue by staybueno** [kyleshay/DIM#185]
![sdsdsddsdsdsd](https://cloud.githubusercontent.com/assets/13475324/8864090/131f2b00-316c-11e5-8884-78913b16029e.PNG)

Thats how my DIM looks like right now. It just happened and even after uninstalling it and installing it back again, it still looks like this. hielp :'v

**Comment by SunburnedGoose** [comment]
Fixed already with #184.  You have to put a piece of gear on your level 20 guardians to get them to 21 or greater.  

btw, this is an issue with Bungie.  https://twitter.com/BungieHelp/status/624335394130264064
