### ISSUE TITLE
analytics and donations received

### ISSUE THREAD

**Issue by kyleshay** [kyleshay/DIM#22]
Hey All!

Figured I'd talk about this really quick.

Here is a link to some user information: https://imgur.com/rc9QtGS

So far my paypal has racked up nearly $80. I'm keeping track of the funds gained (and the user's notes.) in a spreadsheet.

Publishing a chrome extension required a $5 fee. Other than that, there is still some money sitting around. 

I figured that I'd just let it sit until we need something. If we ever stand up a site, or need to invest in some sort of collaboration tool beyond github itself, I would use the funds for that.

Let me know your thoughts and take care.

Kyle

**Comment by SunburnedGoose** [comment]
Sounds good.
