### ISSUE TITLE
Code refactoring?

### ISSUE THREAD

**Issue by alessioalex** [kyleshay/DIM#24]
It would be nice to have the code more organized with something like [Browserify](http://npm.im/browserify) for example.

Would you be open to this?

**Comment by SunburnedGoose** [comment]
It isn't a large enough project to need Browserify.  We use all the scripts we're loading, and minification will bring them in a single file.

At the moment, we don't even have a task runner.

**Comment by alessioalex** [comment]
I didn't suggest it for minification purposes (since that's unnecessary), but I think we would benefit from the CommonJS `require` system.

Currently the `main.js` file has over 800 LOC in it. It's a bit hard to read. Even if we split it into 5 file we would have to keep including them in the `index.html` page. By using something like Browserify we can easily split it up and even possibly use modules from NPM.

It would indeed require a bundling step, but that wouldn't be so hard in my opinion.

**Comment by SunburnedGoose** [comment]
We've got a fork to move it to Angular.  https://github.com/SunburnedGoose/DIM

My goal atm is to break up main.js into directives and services.  I feel your pain looking at main.js.

**Comment by alessioalex** [comment]
That's a good effort, however this will eliminate the need to including a lot of files by hand: https://github.com/SunburnedGoose/DIM/blob/master/window.html#L72-L89

Also (this is just my opinion) I think it would be better to keep this with just raw JavaScript, since Angular may be a barrier to other contributions (such as it would be for me).

I don't mean to be rude, I really appreciate your work.

**Comment by JordanForeman** [comment]
Just found this repo today, so hopefully I'll be making some PRs soon...I agree with @alessioalex  that Angular is probably a little heavy-handed for a project like this. That said, a basic AMD approach using something like [RequireJS](http://requirejs.org/) might make a bit more sense, and would introduce the desired modularity. I haven't used CommonJS personally, but from some initial digging, it seems like it might be a bit much as well.

**Comment by SunburnedGoose** [comment]
Either you use <scripts> or require(..), gotta refer to the code somewhere by hand.

Raw javascript was building up friction the larger it was growing.  Sometimes the HTML didn't match the data model because there was an error.  Looking at main.js, you see that about 2/3rds of it is manipulating HTML on load and while responding to events.  We're going to cut that way down and make the view model logic clearer.

**Comment by SunburnedGoose** [comment]
Either you use scripts**

**Comment by kyleshay** [comment]
angularjs port is in development.

https://github.com/SunburnedGoose/DIM

will allow for a more organized workflow.
