### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by JordanForeman** [kyleshay/DIM#27]
Reddit is a beautiful thing, but it is not meant to serve as documentation. At the very least, the README file needs to be updated, as right now it tells me next to nothing.

Some suggestions:
- Build requirements?
- How to test changes locally?
- Contribution requirements?

**Comment by alessioalex** [comment]
Exactly, I was thinking of that as well when I first took a look at this repo. Particularly the `How to test changes locally?` part.

I would love to help out btw, with whatever would be needed.

**Comment by SunburnedGoose** [comment]
I agree.  All of our hands are full atm, so feel free to make a README.  As soon as I get the fork done with Angular, I was going to pivot to adding a task runner to the project. I don't have a preference regarding the feature sets of grunt or gulp.  I would defer to the volunteer who takes on the task.  If I were to do it, it would be grunt as I'm more familiar. 

From there, we can start looking at Karma and Jasmine test runners.  I can get some specs written to test the controllers and services.

**Comment by kyleshay** [comment]
Task runner will be really great to have. I'm not totally familiar with using gulp myself. Maybe we can use this as a learning experience. :)

Then let's throw protractor on this! Haha, ha.

**Comment by kyleshay** [comment]
changes are eventually coming down the pipeline (since it req's to build will all change anyway):
https://github.com/polyesterhat/DIM/blob/master/README.md
