### ISSUE TITLE
[Suggestion] Add License (or not)

### ISSUE THREAD

**Issue by JordanForeman** [kyleshay/DIM#28]
This isn't my decision to make, so @kyleshay do what you will. But there [are implications](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) of not licensing your code. It looks like this repo is fairly popular, and if it continues to pick up traction you might want to consider adding a license. [choosealicense.com](http://choosealicense.com/) is a pretty great resource for this.

This is really just a suggestion, and you can definitely keep this code unlicensed if you want, in which case you can just mark this issue as resolved.

**Comment by SunburnedGoose** [comment]
+1

**Comment by kyleshay** [comment]
Any suggestions are welcome!

**Comment by SunburnedGoose** [comment]
MIT is what I use most often, just requires attribution for your original work.  GPL requires that anyone who uses your code must be open-source too.

**Comment by loganfuller** [comment]
+1 for MIT
