### ISSUE TITLE
[Suggestion] Set up a Gitter.im room for easier discussion

### ISSUE THREAD

**Issue by loganfuller** [kyleshay/DIM#33]
I use [Gitter](https://gitter.im) a lot for my own repos, and it's been adopted by a lot of large OSS projects as an alternative to IRC. The Gitter room could be kept as dev-focused discussion, while the subreddit would remain the primary point of contact with DIM's users.

Would simply require @kyleshay adding the repo on [Gitter](https://gitter.im) and adding a badge to the project's README.

**Comment by SunburnedGoose** [comment]
We've setup a place on Slack for the conversation.

**Comment by kyleshay** [comment]
how can we have people use our slack board? do we need to approve them, or can they just join the discussion?

destinyitemmanager.slack.com

**Comment by loganfuller** [comment]
That's one of the things I really like about Gitter - you don't have to worry about inviting people and such. I'm good with either though.

**Comment by kruegerb** [comment]
:+1: for Gitter.  Slack just seems to be too heavy-handed for a project like this.

**Comment by SunburnedGoose** [comment]
It seems like Gitter has only one room for chat around the repo.  Is there support for rooms to have side conversations?  What is the discover-ability for those rooms for new people just joining the conversation?

**Comment by loganfuller** [comment]
Gitter is intended to emulate an IRC room, only tightly integrated to a Github repo, so there is no support for project-level side conversations. You can have private chats with individual users in the room though, and you can set up your own channels for topic-specific chats.

**Comment by SunburnedGoose** [comment]
Thanks.

**Comment by kyleshay** [comment]
gitter created
