### ISSUE TITLE
Cleaning up main.js / rendering / organization...

### ISSUE THREAD

**Issue by ivanstojic** [kyleshay/DIM#35]
Could we clean up the architecture a tad? I'm not the biggest fan of MV<whatever> frameworks, but I figure a lil bit of templating and reengineering could be good for everyone who will want to contribute in the future?

The subreddit mentions that there's an Angular.js version somewhere awaiting a pull, and was suggesting that it'll be pulled soon. Any progress? Can I help somehow?

**Comment by SunburnedGoose** [comment]
I've been working on the Angular port. I've broken up main.js and spread it
out across directives and services. The app is now responding to changes to
data binding.

What is not as much fun is writing unit tests. :/

When I get off my phone, I'll post the link to my branch.

**Comment by kyleshay** [comment]
https://github.com/SunburnedGoose/DIM

**Comment by SunburnedGoose** [comment]
https://github.com/SunburnedGoose/DIM/tree/promises-angular
