### ISSUE TITLE
Wrong screen layout

### ISSUE THREAD

**Issue by crasberry** [kyleshay/DIM#5]
![screen shot 2015-03-05 at 11 21 26](https://cloud.githubusercontent.com/assets/11333419/6506465/07c1edd4-c32a-11e4-8267-da072a08357b.png)

From the screen shots on the original post in reddit I believe each character should show as its own column, with items underneath. For me it shows one on top of the other as you can see in the attached image.

my system specs:
Destiny Item Manager Version 2.0.1
Chrome Version 41.0.2272.76 (64-bit)
MacBook Pro OSX Yosemite Version 10.10.2

**Comment by TopDawggamer** [comment]
I believe this is just a feature for smaller screen sizes.

**Comment by kyleshay** [comment]
patched to only display column layouts
