### ISSUE TITLE
Combine Like Materials and Consumables

### ISSUE THREAD

**Issue by SunburnedGoose** [kyleshay/DIM#52]
If I transfer 3 sapphire to the vault, and I have a stack of 19 sapphire, then I need to end up with a stack of 20 sapphire and one stack of 2 sapphire.  

Currently it just shows a stack of 19 and a stack of 3.

**Comment by Subject22** [comment]
Sapphire Wire seems to stack infinitely, and so you should end up with a stack of 22 sapphire wire. Planetary materials like spirit bloom and relic iron exhibit this issue, however.

**Comment by SunburnedGoose** [comment]
Sure, just an example.  We have the max stack size from the items def, we just don't use them yet.

**Comment by Subject22** [comment]
Oh really? Cool. I was wondering about that and feared that it would have to be hard coded and manually updated :P
