### ISSUE TITLE
When scrolled down the page it's hard to tell which character is which

### ISSUE THREAD

**Issue by Subject22** [kyleshay/DIM#55]
Issue
-------
When scrolled past the top of the page it's tricky to tell which column refers to which character. This issue is particularly bad with the V3 interface as the page is much longer and, particularly towards the bottom, the sections do not contain class-specific items.

Possible Solution
----------------------
Freeze the character bar. The topmost bar (the one containing the search box) stays in place when the page is scrolled. Do the same thing to the bar which contains the character emblems.

**Comment by brandonkboswell** [comment]
This seems like it could be useful.

**Comment by AAraKKe** [comment]
I tottaly would vote for fixing the character row on the top of the script like a navbar.

**Comment by SunburnedGoose** [comment]
This is planned for v4.
