### ISSUE TITLE
No clear search field button

### ISSUE THREAD

**Issue by Andydigital** [kyleshay/DIM#56]
As the subject says and probably just an oversight or future addition, there is no clear search field button like in earlier versions.

**Comment by SunburnedGoose** [comment]
Can you attach an image of the button in the earlier versions?  I don't see one.  

afaik, it's always been a input field and the search executes as you type.

**Comment by Andydigital** [comment]
Here ya go;
https://www.dropbox.com/s/hfmg0hm2kvozfzu/Screenshot%202015-04-29%2008.20.16.png

**Comment by SunburnedGoose** [comment]
What do you see now?

http://i.imgur.com/N7S9A85.png

This is my screen which has the search filter.

**Comment by Andydigital** [comment]
I see the searchbox then my username for the google account and thats it, there is no option to choose xbox or psn on my version. I only have destiny on ps4 though if that makes any difference.

**Comment by SunburnedGoose** [comment]
Can you send me a screen shot of the app?  Does the name match your PSN Account?  I only show the drop down when you have multiple platforms to choose from in Destiny.  If you only have your PSN account associated with Bungie.net, then that is all you will see in DIM.

**Comment by Andydigital** [comment]
Yes the name matches my PSN account.
https://www.dropbox.com/s/8s9mnzrba3g7wki/Screenshot%202015-04-29%2008.41.42.png

**Comment by Andydigital** [comment]
Only one exotic missing from my collection, Jellyhorn ;)

**Comment by SunburnedGoose** [comment]
I'm gonna close this issue then.  Not having the drop down is an expected behavior.  Feel free to reopen it if there is a problem with swapping platforms.

I just got my Thunderlord last week.  Felt good.  

Good hunting.

**Comment by Andydigital** [comment]
The drop down wasn't the issue, the X button to clear the search field was the issue ;)

**Comment by SunburnedGoose** [comment]
I'm using normalize.css which makes all browsers behave the same.  Sometimes that means that they must have the lowest-common features.  This removed the clear button from the search field.  I'll add it back.

**Comment by SunburnedGoose** [comment]
Fixed and added to the branch.
