### ISSUE TITLE
Loadouts and transfering in v3

### ISSUE THREAD

**Issue by AAraKKe** [kyleshay/DIM#57]
It might be me that I don't know how to do this but I have several problems:

When creating a loadout I cannot select which item to equip (which I thought was possible), isn't it just click on the item you want to equip?
I am not able to actually transfer a loadout. I select the loadout in the dropdown of the character that I want and it doesn't transfer or any menu pops up to let me choose.

Another issue I have noticed is that there is no clue if something is trasferring or not. Could it be added some kind of dialog telling what items are being transferred or are left to transfer? Sometimes it gets stuck for a couple of second and I always think it has crashed.

EDIT: It seems that the loadouts are transferring but for some reason sometimes I need to click several times in order to transfer it.

**Comment by SunburnedGoose** [comment]
At the moment, the text of the loadout name is the only spot that actually fires off the transfer, even though the box had an indicator that you can click.

Can you confirm if that is the case?  I tried to fix that last night but it wasn't ready to go yet.

**Comment by AAraKKe** [comment]
Yeps, that's right. I wasn't clicking on the name ;)
