### ISSUE TITLE
Background Image Performs Oddly

### ISSUE THREAD

**Issue by brandonkboswell** [kyleshay/DIM#59]
Chrome 42.0.2311. 13" Retina Macbook.

![screenshot 2015-04-29 09 25 59](https://cloud.githubusercontent.com/assets/921925/7391854/fb982c96-ee51-11e4-8697-cc7abad017d6.png)

**Comment by SunburnedGoose** [comment]
Yesterday was the first day I've noticed that tearing too.  I don't know what's going on there...  It only happened once so I wasn't able to debug it.

**Comment by brandonkboswell** [comment]
@SunburnedGoose yeah, it's not all the time, but is frequent. Perhaps just moving to a background-gradient is an easier, more robust solution.
