### ISSUE TITLE
Transfer & Loadout issues V3

### ISSUE THREAD

**Issue by matthewk85** [kyleshay/DIM#68]
A couple issues have come up trialing V3
1. I create a loadout with a specific set of armor. When i select the loadout, the chest peice and gloves have changed to a different pair. I have tried deleting the loadout and creating a new one, but the same issue occured.
2. In attempting to equip a set of gloves (both individually and in a loadout) i get the following error "Your character is not experienced enough to use this item... yet". The character i am transfering to is level 31 and should be capable of being equipped.

Otherwise this is looking to be an ace update. Keep up the good work.

**Comment by SunburnedGoose** [comment]
Thanks for the description.  It's related to #63.
