### ISSUE TITLE
Infinite loading still an issue

### ISSUE THREAD

**Issue by acepilot1023** [kyleshay/DIM#7]
I'm posting here so it'll be easier to keep track of.

I'm running the latest chrome update along with the latest (v2.1) DIM version.

I never get the chance to log in, just stare at the infinite loading screen. There are also no errors in the dev console.

http://puu.sh/gnyAH/9238d92b65.png

**Comment by TopDawggamer** [comment]
Are you logged into Bungie.net? Also what system do you play on?

**Comment by acepilot1023** [comment]
Yes, and 360.

**Comment by kyleshay** [comment]
could you hit the network tab ?

on bungie.net do you have a PSN and XBL user linked?

**Comment by acepilot1023** [comment]
I've never had a PSN account nor does anyone in my household so that's not the issue

**Comment by kyleshay** [comment]
still an issue? have you been able to resolve it/did it resolve it self?

**Comment by kyleshay** [comment]
assuming this has been resolved - closing for now.
