### ISSUE TITLE
Suggestion: Automatic refresh

### ISSUE THREAD

**Issue by Subject22** [kyleshay/DIM#70]
Changing the state of one of my inventories or Vault from within Destiny itself leaves DIM in an inconsistent state. Attempting to move an item in DIM which has already been moved within the game, or doing something which prompts DIM to attempt to make such a change itself (eg: when shuffling items around to make space) causes an error.

DIM could automatically check its state in the background and update the UI as necessary every few minutes (or some other amount of time, which is palatable to Bungie). Alternatively, DIM could self-refresh after an error and attempt to repeat the failed operation, just in case the problem was simply an inconsistent state.

**Comment by SunburnedGoose** [comment]
Added in v3.0.12.
