### ISSUE TITLE
Laytout issue in V3 beta 2

### ISSUE THREAD

**Issue by AAraKKe** [kyleshay/DIM#72]
As you can see consumables are well located, i.e. if one of the characters has more rows the next category is well placed but it seems not to be the case below consumables where you can see that the emblems start higher for the two last characters.
![screen shot 2015-05-01 at 11 31 34](https://cloud.githubusercontent.com/assets/2953658/7429221/ed2b418e-eff5-11e4-9a0a-e787ad6c9636.png)

**Comment by SunburnedGoose** [comment]
Fixed it in commit b153a93.  It is in Beta 2 which is available to download.

https://github.com/kyleshay/DIM/releases/tag/v3.0.0-beta.2
