### ISSUE TITLE
Drag and drop issues in V3b3

### ISSUE THREAD

**Issue by Subject22** [kyleshay/DIM#77]
In the latest beta I don't seem to be able to drag and drop items to move them. I can drag and drop to equip (including between characters), but not to move. I also note that the nice little animated highlights no longer appear when I start dragging an item. 

No errors are displayed by the UI or by the console.

**Comment by SunburnedGoose** [comment]
Look at that...  Thanks, I fixed it.  Messed that up trying to fix the highlighting.

**Comment by Subject22** [comment]
Awesome :) You're on a hell of a development spree at the moment!

**Comment by SunburnedGoose** [comment]
Are you comfortable running 'bower' and pulling the code directly from the repo?

**Comment by Subject22** [comment]
Yep. Want me to test it? I'll give it a shot now.

**Comment by SunburnedGoose** [comment]
Let me push, one moment.

**Comment by SunburnedGoose** [comment]
Pushed.  Go ahead and pull.

**Comment by SunburnedGoose** [comment]
Meet me over here, https://gitter.im/kyleshay/DIM
