### ISSUE TITLE
Transferring general items to vault does not stack them until refresh 

### ISSUE THREAD

**Issue by bobonaut** [kyleshay/DIM#86]
Whenever i transfer a general item i.e.: ascendant shards, motes of light, strange coins etc. the vault gets updated but there are two stacks in the vault.
![dim v3 - before transfer](https://cloud.githubusercontent.com/assets/4076121/7542212/4145fd02-f5bb-11e4-921f-bccb5bb1a329.jpg)
![dim v3 - after transfer](https://cloud.githubusercontent.com/assets/4076121/7542213/4424d46c-f5bb-11e4-89d7-9f7c9fd45f33.jpg)
![dim v3 - after refresh](https://cloud.githubusercontent.com/assets/4076121/7542215/45860bb4-f5bb-11e4-9016-27cf2cb6545a.jpg)

**Comment by kyleshay** [comment]
thanks for documenting this issue with images. 

 A+ issue report. 

thank you! :+1:

**Comment by SunburnedGoose** [comment]
Echoed. We'll get that fixed.

**Comment by c-nichols** [comment]
Happens also when transferring e.g., spinmetal from one character to another character who already has spinmetal in inventory.

**Comment by SunburnedGoose** [comment]
Happens with any stackable item.
