### ISSUE TITLE
Suggestions: Fixed Header for Emblem, Column Separator between Guardians

### ISSUE THREAD

**Issue by shornby** [kyleshay/DIM#89]
First of all - DIM is an excellent Chrome Extension!
Suggestions:
It would help if the emblem were visible all the time, if possible - like very narrow fixed header.  Also, having a separator would really make it easier to identify information on the page.  Even simple divider lines between the three Guardian columns would really help.

If this suggestion belongs in Reddit, my apologies.  Let me know and I'll delete this one.

**Comment by Subject22** [comment]
Your suggestion sounds a lot like mine, which is apparently coming in V4 :) 

https://github.com/kyleshay/DIM/issues/55

**Comment by shornby** [comment]
Great minds think alike :)

Btw- any reason this is an extension, and not an app?  Probably would get more exposure that way.  For Chromebook users, it would get its own icon in the taskbar...
Thx,
S

**Comment by Subject22** [comment]
No idea. I've never so much as laid eyes on a Chromebook and I only really use Chrome for this extension. V4 is said to include support for other browsers and platforms (iOS, Android, Windows Phone etc.) though.

**Comment by MSPRvrView** [comment]
I was just going to submit the same suggestion. Great app!
