### ISSUE TITLE
Bring back loadout bulider

### ISSUE THREAD

**Issue by matthewk85** [kyleshay/DIM#93]
The armor load-out builder was a fantastic tool. I have just one suggestion with it; be able to select an exotic armor piece to build an armor load-out around - will make it just that bit better.

Love V3 BTW!

**Comment by SunburnedGoose** [comment]
Becoming by a standalone app. We can make the apps work together like that.

**Comment by matthewk85** [comment]
Awesome, look forward to it. Ace work.

**Comment by wein3967** [comment]
I didn't realize there was a load-out generator in the previous version. Was it a stat optimizer? I ended up writing my own in VB.NET awhile back, since I couldn't seem to find one. Looking forward to checking it out. I'm really enjoying v3. Thanks for all the excellent work.
