### ISSUE TITLE
Enhancement: Filter by Duplicates

### ISSUE THREAD

**Issue by m-s-y** [kyleshay/DIM#97]
Enable functionality to identify duplicate equipable items (by item name, not by item perk list).  For example

is:duplicate

Currently, I can identify all of my Crota's End armor duplicates by the query "is:death" (see attached), but it only works because I know the item name.  Would be nice to be able to identify all duplicates regardless of the item name.

![2015-05-11_12-18-16](https://cloud.githubusercontent.com/assets/6401354/7569620/fb7367fa-f7d7-11e4-98a4-eea3880414dc.png)

**Comment by SunburnedGoose** [comment]
Pretty straight forward.  Good idea.

**Comment by phatsk** [comment]
@SunburnedGoose I could take a look at this - having fun in the code so far

**Comment by SunburnedGoose** [comment]
Sure.  There is also an issue out for is:stackable.  Just look for items
where (item.maxStackSize > 1).

**Comment by phatsk** [comment]
@SunburnedGoose I've got this working for all items except the first item in the set. How can I reset the visibility for an item that has already been determined to not be in the filter, but then is retroactively set as visible? Here's a screenshot:

![screen shot 2015-05-13 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/990374/7618995/df20b096-f983-11e4-8e43-0b69b65f3b28.png)

JS:

````javascript
result = function(p, item) {
  if(!_duplicates.hasOwnProperty(item.hash))
    _duplicates[item.hash] = {count: 1, hash: item.hash};
  else
    _duplicates[item.hash].count++;

  return _duplicates[item.hash].count < 2;
};
````

So, the first time I hit the else, I need to go back and mark the item with the hash in the `_duplicates[item.hash]` object and switch it's visibility. Thoughts?

**Comment by SunburnedGoose** [comment]
This is how I wrote it.  I generate a property on _duplicate that is a list of all hashes that are duplicate.  I only do it once during search.  I then compare every item against that collection.


        case 'dupe':
          {
            result = function(p, item) {
              if (!_duplicates.hasOwnProperty('dupes')) {
                var allItems = _.chain(dimStoreService.getStores())
                  .map(function(store) {
                    return store.items;
                  })
                  .flatten()
                  .value();

                var sortedItems = allItems.sort(function compare(a, b) {
                  if (a.hash < b.hash) {
                    return -1;
                  }
                  if (a.hash > b.hash) {
                    return 1;
                  }
                  return 0;
                });

                _duplicates.dupes = [];
                for (var i = 0; i < sortedItems.length - 1; i++) {
                  if (sortedItems[i + 1].hash == sortedItems[i].hash) {
                    _duplicates.dupes.push(sortedItems[i].hash);
                  }
                }
              }

              return !_.some(_duplicates.dupes, function(hash) { return item.hash === hash; });
            };
            break;
          }

Using the filter criteria, *is:dupe is:primary is:legendary*, I get

![2015-05-13_165204](https://cloud.githubusercontent.com/assets/984608/7621965/75ca7822-f990-11e4-87f4-44f8f18e1e54.jpg)

**Comment by phatsk** [comment]
Oh dang, already got it sorted out then? Nice!

**Comment by SunburnedGoose** [comment]
Well, I took your code and added to it ;)

**Comment by phatsk** [comment]
Good stuff :) Also, let me know if you have any questions on the pull request for 94/101.
